// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjvnhgjjxcvebxnpahan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqdm5oZ2pqeGN2ZWJ4bnBhaGFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjUxNDgsImV4cCI6MjA3MDMwMTE0OH0.VcxxqtoJUegA9U1jl7Uz3AOwshlc7Wtub46lz99CgqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});